[font]
normal = {family = "MesloLGM Nerd Font", style="Regular"}

[window]
startup_mode = "Windowed"
opacity = 0.95
padding = {x = 10, y=5}

[selection]
save_to_clipboard = true

[env]
TERM = "alacritty"

[[hints.enabled]]
regex = "[^ ]+\\.rs:\\d+:\\d+"
command = { program = "code", args = [ "--goto" ] }
mouse = { enabled = true }
binding = { key = "O", mods = "Control|Shift" }

[[hints.enabled]]
command = "xdg-open" # On Linux/BSD
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "O", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

[keyboard]
bindings = [
# Tmux window navigation
{key = "1", mods="Alt", chars =  "\u00021"  },
{key = "2", mods="Alt", chars =  "\u00022"  }, 
{key = "3", mods="Alt", chars =  "\u00023"  }, 
{key = "4", mods="Alt", chars =  "\u00024"  }, 
{key = "5", mods="Alt", chars =  "\u00025"  }, 
{key = "6", mods="Alt", chars =  "\u00026"  }, 
{key = "7", mods="Alt", chars =  "\u00027"  }, 
# Also with the arrows
{key = "ArrowLeft", mods="Alt", chars =  "\u0002\u0070"  }, 
{key = "ArrowRight", mods="Alt", chars =  "\u0002\u006e"  }, 
# Tmux pane navigation
{key = "h", mods="Alt", chars =  "\u0002h"  },
{key = "j", mods="Alt", chars =  "\u0002j"  },
{key = "k", mods="Alt", chars =  "\u0002k"  },
{key = "l", mods="Alt", chars =  "\u0002l" },
# More pane shortcuts
{key = "x", mods="Alt", chars =  "\u0002x" },
# Tmux copy mode
{key = "v", mods="Alt", chars =  "\u0002[" },
{key = "y", mods="Alt", chars =  "\u0002]" },
# nvim shortcuts
# {key = "w", mods="Alt", chars =  "\u001b:wa\n" },
# {key = "q", mods="Alt", chars =  "\u001b:qa\n" },
]
