[font]
normal = {family = "MesloLGM Nerd Font", style="Regular"}

[window]
startup_mode = "Windowed"
opacity = 0.95
padding = {x = 10, y=5}

# [selection]
# save_to_clipboard = true
[env]
term = "xterm-256color"

[[hints.enabled]]
regex = "[^ ]+\\.rs:\\d+:\\d+"
command = { program = "code", args = [ "--goto" ] }
mouse = { enabled = true }
binding = { key = "O", mods = "Control|Shift" }

[[hints.enabled]]
command = "xdg-open" # On Linux/BSD
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "O", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

[keyboard]
bindings = [
# Quick tmux window navigation
{key = "1", mods="Alt", chars =  "\u0002\u0031"  }, 
{key = "2", mods="Alt", chars =  "\u0002\u0032"  }, 
{key = "3", mods="Alt", chars =  "\u0002\u0033"  }, 
{key = "4", mods="Alt", chars =  "\u0002\u0034"  }, 
{key = "5", mods="Alt", chars =  "\u0002\u0035"  }, 
{key = "6", mods="Alt", chars =  "\u0002\u0036"  }, 
{key = "7", mods="Alt", chars =  "\u0002\u0037"  }, 
{key = "8", mods="Alt", chars =  "\u0002\u0038"  }, 
{key = "9", mods="Alt", chars =  "\u0002\u0039"  }, 
# Quick tmux pane navigation
{key = "h", mods="Alt", chars =  "\u0002\u0068"  },
{key = "j", mods="Alt", chars =  "\u0002\u006a"  },
{key = "k", mods="Alt", chars =  "\u0002\u006b"  },
{key = "l", mods="Alt", chars =  "\u0002\u006c" },
]
