[font]
normal = {family = "MesloLGM Nerd Font", style="Regular"}

[window]
startup_mode = "Windowed"
opacity = 0.95
padding = {x = 10, y=5}

# [selection]
# save_to_clipboard = true
[env]
term = "xterm-256color"

[keyboard]
bindings = [
{key = "1", mods="Alt", command= { program = "tmux", args = ["select-window", "-t", "1"]}},
{key = "2", mods="Alt", command= { program = "tmux", args = ["select-window", "-t", "2"]}},
{key = "3", mods="Alt", command= { program = "tmux", args = ["select-window", "-t", "3"]}},
{key = "4", mods="Alt", command= { program = "tmux", args = ["select-window", "-t", "4"]}},
{key = "5", mods="Alt", command= { program = "tmux", args = ["select-window", "-t", "5"]}},
{key = "6", mods="Alt", command= { program = "tmux", args = ["select-window", "-t", "6"]}},
{key = "7", mods="Alt", command= { program = "tmux", args = ["select-window", "-t", "7"]}},
{key = "8", mods="Alt", command= { program = "tmux", args = ["select-window", "-t", "8"]}},
{key = "9", mods="Alt", command= { program = "tmux", args = ["select-window", "-t", "9"]}},
{key = "h", mods="Alt", command= { program = "tmux", args = ["select-pane", "-L"]}},
{key = "j", mods="Alt", command= { program = "tmux", args = ["select-pane", "-D"]}},
{key = "k", mods="Alt", command= { program = "tmux", args = ["select-pane", "-U"]}},
{key = "l", mods="Alt", command= { program = "tmux", args = ["select-pane", "-R"]}},
]
