# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="ducknorris"
COMPLETION_WAITING_DOTS="true"

plugins=(emoji encode64 colorize colored-man-pages rust virtualenv docker)

source $ZSH/oh-my-zsh.sh

# key bindings
bindkey ' ' magic-space                           # do history expansion on spacebindkey
bindkey '^U' backward-kill-line                   # ctrl + U
# bindkey '^[[3;5~' kill-word                       # ctrl + Supr
# bindkey '^[[3~' delete-char                       # delete
bindkey '^o' forward-word
bindkey '^h' backward-word
# bindkey '^[[5~' beginning-of-buffer-or-history    # page up
bindkey '^[[6~' end-of-buffer-or-history
bindkey '^a' beginning-of-line
# bindkey '^[[F' end-of-line                        # end
# bindkey '^[[Z' undo                               # shift + tab undo last action

# Brew
eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

# Rust defines
export RUST_LOG="debug"

#Android studio path:
export PATH=$PATH:/usr/local/android-studio
export PATH=$PATH:/usr/local/go/bin

# https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/INSTALL.md
source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
ZSH_HIGHLIGHT_HIGHLIGHTERS+=(brackets pattern)

# https://github.com/zsh-users/zsh-autosuggestion
source /home/linuxbrew/.linuxbrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh
bindkey '^f' autosuggest-accept
bindkey '^e' autosuggest-execute
bindkey '^w' forward-word
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=8,italic,underline"

# Go path
export GOPATH=$HOME/go
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin

# Generic aliases
alias compress-pics='find . -iname "*.jpg" -exec convert {} -resize 1200x {} \;'
alias install-discord='find ~/Downloads -iname "discord*.deb" -exec sudo dpkg -i {} \; -exec rip {} \;'
alias install-updates='sudo apt update && sudo apt upgrade -y && sudo apt autoremove -y'

# Git aliases
alias gf="git fetch --all -p"
alias gl="git log --oneline"
alias gp="git pull"
alias gbr="git branch -vv"

# Some eza shortcuts
alias l="eza --icons --git"
alias ll="l --long"
alias la="l --all"
alias lla="l --long --all"

# ip with colors
alias ip="ip --color=auto"

# Fzf
source <(fzf --zsh)
alias fz="fzf --preview 'bat --color=always {}' --preview-window '~3'"
alias ff="find * | fzf --preview 'bat --color=always {}' --preview-window '~3' --prompt 'All> ' --header 'CTRL-D: D:irectories / CTRL-F: Files' --bind 'ctrl-d:change-prompt(Directories> )+reload(find * -type d)' --bind 'ctrl-f:change-prompt(Files> )+reload(find * -type f)'"
alias fo="fz --bind 'enter:execute(nvim {})'"

fh() {
  print -z $( ([ -n "$ZSH_NAME" ] && fc -l 1 || history) | fzf +s --tac | sed -E 's/ *[0-9]*\*? *//' | sed -E 's/\\/\\\\/g')
}

fkill() {
  local pid
  if [ "$UID" != "0" ]; then
    pid=$(ps -f -u $UID | sed 1d | fzf -m | awk '{print $2}')
  else
    pid=$(ps -ef | sed 1d | fzf -m | awk '{print $2}')
  fi 

  if [ "x$pid" != "x" ]
  then
    echo $pid | xargs kill -${1:-9}
  fi 
}

if [[ "$(uname)" == "Darwin" ]]; then
    # MacOS specific settings
    echo "Running on macOS"
    alias copy="pbcopy"
    alias paste="pbpaste"
elif [[ "$(uname)" == "Linux" ]]; then
    # Linux settings
    # Keyboard overdrive
    xset r rate 175 30
    # Map Caps-locks to Es
    setxkbmap -option caps:escape
    #Copy/paste
    alias copy="xsel --input --clipboard"
    alias paste="xsel --output --clipboard"
fi

# History configuration
HISTZISE=10000
HISTFILE=~/.zsh_history
SAVEHIST=$HISTZISE
HISDUP=erase
setopt appendhistory
setopt sharehistory
setopt hist_ignore_space
setopt hist_ignore_all_dups
setopt hist_save_no_dups
setopt hist_ignore_dups
setopt hist_find_no_dups

# Completion styling
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"


# Install rust
if !rustup --version &> /dev/null
then
    echo "Installing rust"
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
fi

# Starship
#export STARSHIP_CONFIG=~/.config/starship.toml
if !starship --version &> /dev/null
then
    echo "Installing starship"
    curl -sS https://starship.rs/install.sh | sh
fi
eval "$(starship init zsh)"

# Zoxide
if !zoxide --version &> /dev/null
then
  echo "Installing zoxide"
    curl -sSfL https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | sh
fi
eval "$(zoxide init --cmd j zsh)"


if !delta --version &> /dev/null
then
    echo "Installing git-delta"
    cargo install git-delta
fi

if !atuin --version &> /dev/null
then
    echo "Installing atuin"
    cargo install atuin
fi

# Added by alacritty
fpath+=${ZDOTDIR:-~}/.zsh_functions

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
