# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
#ZSH_THEME="robbyrussell"
ZSH_THEME="ducknorris"

POWERLEVEL9K_DISABLE_RPROMPT=true
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLINE_DETECT_SSH="true"
POWERLINE_GIT_CLEAN="✔"
POWERLINE_GIT_DIRTY="✘"
POWERLINE_GIT_ADDED="%F{green}✚%F{black}"
POWERLINE_GIT_MODIFIED="%F{blue}✹%F{black}"
POWERLINE_GIT_DELETED="%F{red}✖%F{black}"
POWERLINE_GIT_UNTRACKED="%F{yellow}✭%F{black}"
POWERLINE_GIT_RENAMED="➜"
POWERLINE_GIT_UNMERGED="═"

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
COMPLETION_WAITING_DOTS="true"

plugins=(emoji encode64 colorize colored-man-pages rust virtualenv)
source $ZSH/oh-my-zsh.sh

# Brew
eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

# Rust defines
export RUST_LOG="debug"

#Android studio path:
export PATH=$PATH:/usr/local/android-studio
export PATH=$PATH:/usr/local/go/bin

# https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/INSTALL.md
source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
ZSH_HIGHLIGHT_HIGHLIGHTERS+=(brackets pattern)

# https://github.com/zsh-users/zsh-autosuggestion
source /home/linuxbrew/.linuxbrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh
bindkey '^f' autosuggest-accept
bindkey '^e' autosuggest-execute
bindkey '^w' forward-word

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=8,italic,underline"

# Go path
export GOPATH=$HOME/go
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin

# Generic aliases
alias compress-pics='find . -iname "*.jpg" -exec convert {} -resize 1200x {} \;'
alias install-discord='find ~/Downloads -iname "discord*.deb" -exec sudo dpkg -i {} \; -exec rip {} \;'

# Some eza shortcuts
alias l="eza --icons --git"
alias ll="l --long"
alias la="l --all"
alias lla="l --long --all"

# Fzf
alias fz="fzf --preview 'bat --color=always {}' --preview-window '~3'"
alias ff="find * | fzf --preview 'bat --color=always {}' --preview-window '~3' --prompt 'All> ' --header 'CTRL-D: D:irectories / CTRL-F: Files' --bind 'ctrl-d:change-prompt(Directories> )+reload(find * -type d)' --bind 'ctrl-f:change-prompt(Files> )+reload(find * -type f)'"
alias fo="fz --bind 'enter:execute(nvim {})'"

# Find history
fh() {
  print -z $( ([ -n "$ZSH_NAME" ] && fc -l 1 || history) | fzf +s --tac | sed -E 's/ *[0-9]*\*? *//' | sed -E 's/\\/\\\\/g')
}

# Kill PIDs
fkill() {
  local pid
  if [ "$UID" != "0" ]; then
    pid=$(ps -f -u $UID | sed 1d | fzf -m | awk '{print $2}')
  else
    pid=$(ps -ef | sed 1d | fzf -m | awk '{print $2}')
  fi

  if [ "x$pid" != "x" ]
  then
    echo $pid | xargs kill -${1:-9}
  fi
}

# Copy/paste
alias copy="xsel --input --clipboard"
alias paste="xsel --output --clipboard"

# https://github.com/wfxr/forgit
source ~/.oh-my-zsh/custom/plugins/forgit/forgit.plugin.zsh

# History configuration
HISTZISE=5000
HISTFILE=~/.zsh_history
SAVEHIST=$HISTZISE
HISDUP=erase
setopt appendhistory
setopt sharehistory
setopt hist_ignore_space
setopt hist_ignore_all_dups
setopt hist_save_no_dups
setopt hist_ignore_dups
setopt hist_find_no_dups

# Completion styling
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"

# Starship
#export STARSHIP_CONFIG=~/.config/starship.toml
if !starship --version &> /dev/null
then
    echo "Installing starship"
    curl -sS https://starship.rs/install.sh | sh
fi
eval "$(starship init zsh)"
